### ISSUE TITLE
Add something to CSS class to not highlight SVG text

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/gw-conditions#64]
![image](https://user-images.githubusercontent.com/13220910/148248136-c1dc4e45-214d-4b08-84d3-ade9e40ec048.png)

**Comment by jread-usgs** [comment]
the waaaaay old way I was doing this in the past was
```css
svg-text {
   -webkit-touch-callout: none; /* iOS Safari */
   -webkit-user-select: none;   /* Chrome/Safari/Opera */
   -khtml-user-select: none;    /* Konqueror */
   -moz-user-select: none;      /* Firefox */
   -ms-user-select: none;       /* Internet Explorer/Edge */
   user-select: none;           /* Non-prefixed version, currently not supported by any browser */
}
```
